### ISSUE TITLE
add location of stuff

### ISSUE THREAD

**Issue by jancborchardt** [shared-stuff/shared-stuff#1]
It should be possible to specify _where_ a specific thing is located, in which city. This would also be useful to have a map or filter by location in the future.

**Comment by shybyte** [comment]
I guess in a first step i would make sense to add a location to a person, as mostly the stuff is where the person is and even if not it would make a good default this way.

**Comment by jancborchardt** [comment]
I thought that as well at first – but in fact it is completely irrelevant where the person is at. If my stuff is in Berlin and I’m travelling, there can still be a way that the stuff can be given to a person, for instance through a flatmate. I’d directly attach the location to the stuff.

**Comment by shared-stuff** [comment]
That's true, but when you travel, you don't have to update your "shared stuff location" and probably most of your stuff is still in  this home location. So while I'm thinking you are right in a theoretical way, most people store all there stuff in one place, which will be their "stuff location".

One could argue, that a other use case might be people who move to a other flat together with all their stuff. These people probably don't want to update the location of all their stuff after the move manually. 

Do you think having a location for the owner (which is displayed for their stuff and is searchable on the friend's stuff page) is a good first step?

**Comment by jancborchardt** [comment]
Yeah, true. Agree that a location for the owner is a good first step. Then you could have an input field on the stuff pages, which defaults to »Home location« and can be changed to something custom if the thing is not where you are.

By the way – for the personal profile data like image and name, we could create a new category named »profile«. That we can also use later in the contacts app.
