### ISSUE TITLE
notification on login site useless, should redirect

### ISSUE THREAD

**Issue by jancborchardt** [shared-stuff/shared-stuff#19]
When someone ends up on http://shared-stuff.github.com/#/login for whatever reason (I just did), they will see a message »You are logged in.«

This notification does not provide any value, instead they should be automatically redirected to http://sharedstuff.org/#/friends-stuff

**Comment by shared-stuff** [comment]
The question is: 
Would somebody enter  http://shared-stuff.github.com/#/login intentionally? 
("I want to login!")
If yes, he might be confused to land on http://sharedstuff.org/#/friends-stuff .

But probably users don't "want to login", they want to use the app and the "login concept" in general just belongs to the annoying  stumbling block in their way.

**Comment by jancborchardt** [comment]
I guess no one would enter that site intentionally. Even if, there are 2 cases:
not logged in → should redirect to /
logged in → should redirect to /friends-stuff (or whatever the logged-in-home site should be)

I logged this issue because I got on that page after a browser restart or so. (The usage of both domains, shared-stuff.github.com and sharedstuff.org in the description was not intentional.)
