### ISSUE TITLE
discern sharing and gifting

### ISSUE THREAD

**Issue by jancborchardt** [shared-stuff/shared-stuff#2]
It should be possible to specify whether you want to give it away or just temporarily share it.

**Comment by shybyte** [comment]
What do you think about the additional options "Sell" and "Use together". "Use together" would mean something we "I don't want to give my gaming console away but come over and we play together".

**Comment by jancborchardt** [comment]
Yeah. »Give away«, »Rent out« and »Use together« would be the 3 stages I would say. Sell could be another one if money should be involved.

**Comment by shared-stuff** [comment]
I wonder if it should be possible to select multiple of this options?
