### ISSUE TITLE
Automated Acceptance Tests

### ISSUE THREAD

**Issue by shared-stuff** [shared-stuff/shared-stuff#21]
Manual testing makes a lot of work and unit tests can't cover everything. Some selenium tests might be a good start.
These will help  to prevent future bugs and act as executable specification. 
Especially if the development of Shared Stuff might be distributed to several people in the future some tests will prevent chaos. 
This case is mainly about starting automated acceptance tests, not about writing a comprehensive  test suite.

**Comment by shybyte** [comment]
My approach to automatic acceptance test is quite cumbersome and brittle. However, I will add new tests while adding new features.
