### ISSUE TITLE
shorten web address

### ISSUE THREAD

**Issue by jancborchardt** [shared-stuff/shared-stuff#4]
It would be cooler to have the public web address shorter, without the invitation just http://shared-stuff.github.com/#user@remotestorage.com

**Comment by shybyte** [comment]
Remote Storage Addresses will always look like an email address, right?

**Comment by jancborchardt** [comment]
Yes, more specifically a webfinger address. But the »invitation« part can be removed from the web address.

**Comment by shared-stuff** [comment]
Deployed to http://shared-stuff.github.com/

**Comment by jancborchardt** [comment]
The address http://sharedstuff.org/#jan@5apps.com doesn’t seem to work when not connected, instead redirecting to http://shared-stuff.github.com/#/login
When connected ("logged in") it works fine.

As it is a public invitation and public stuff, it should work especially when not connected though.

**Comment by shared-stuff** [comment]
Hi Jan, Thanks for the bug report. Should now be fixed on http://shared-stuff.github.com (Maybe you have to clear your browser cache.) 
http://sharedstuff.org has still the first version from last week. Will be updated later this week.
