### ISSUE TITLE
not possible to add someone with no shared stuff

### ISSUE THREAD

**Issue by jancborchardt** [shared-stuff/shared-stuff#6]
When I try to add someone as friend who has no public stuff yet, I get an alert:
»Secret seems invalid. This could mean that your friend has not added public shared stuff yet.«

Instead, that person should just be added to the friends list.

**Comment by shybyte** [comment]
Yes, should be maximal a warning. Stupid Beauvoir with origin in the time where I only thought about private "secret" stuff for close friends.

**Comment by jancborchardt** [comment]
Not even a warning – it’s not relevant for me as a friend if that person has no shared stuff. They will share something eventually and then it will turn up in my feed. I can’t change something about it, so it shouldn’t warn me.

By the way – what exactly is the secret for and how does it work? It seems a bit overcomplicated and like all the secret stuff can be solved by only giving friends access to it?

**Comment by shared-stuff** [comment]
You are probably right about the public stuff.

Without this secret (which creates a secret URL), everyone who has your remoteStorageID can see your stuff. Or is there any access-right-management in remoteStorage, that I haven't figured out?
