### ISSUE TITLE
difference between this and the other repo

### ISSUE THREAD

**Issue by jancborchardt** [shared-stuff/shared-stuff#9]
Isn’t quite apparent – isn’t this repo hosted at shared-stuff.github.com? You can also use different branches, the gh-pages branch will be the one hosted.

**Comment by shared-stuff** [comment]
The shared-stuff.github.com is for the "build" version of the app, which means currently that is uses minified and concatinated libraries, javascripts and stylesheets. This reduces loading time a lot and prevents some cache issues.

**Comment by jancborchardt** [comment]
Ah, ok! Is the [pull request](https://github.com/shared-stuff/shared-stuff.github.com/pull/1) regarding the top level domain correct in the other repo then?

**Comment by shared-stuff** [comment]
Generally all forks (which intend to merge their changes back) should be based on the https://github.com/shared-stuff/shared-stuff repo and not the https://github.com/shared-stuff/shared-stuff.github.com repo.
This repo is the SOURCE.
